// <auto-generated />
using System;
using CoalServices.Carousel.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoalServices.Carousel.Persistence.Migrations
{
    [DbContext(typeof(CoalServicesContext))]
    partial class CoalServicesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoalServices.Carousel.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("VARCHAR(16)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("BIGINT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Images","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
